# Generated by Django 4.2.3 on 2023-08-27 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PGTapp', '0002_reservacion_fecha_reservacion_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50, default='')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña', models.CharField(max_length=50, default='')),
                ('nombre_Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
