# Generated by Django 4.2.3 on 2023-08-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PGTapp', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
