# Generated by Django 4.2.3 on 2023-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGTapp', '0006_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
