# Generated by Django 4.2.3 on 2023-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGTapp', '0007_auto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
    ]
